name: Docker Publish

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Jemetr Base to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./docker/jmeter-base
          push: true
          tags: dishanr/jmeter-base:latest
      - name: Push Jemetr to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./docker/jmeter
          push: true
          tags: dishanr/jmeter:latest
